---
title: "global_data"
author: "Liyenne"
date: "2025-06-03"
output: html_document
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = here::here("outputs")
    )
  })
cache: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Setup
```{r}
# data handling
require(readr)
require(tidyverse)
require(rtry)
require(WorldFlora)

# analysis
require(traitstrap)

# visualization
require(ggplot2)
```

# Data import
```{r data import}
# trait data
traits <- read_csv("2_data/2_clean/traits/traits_w.csv") %>%
  mutate(across(ID:group, as.factor))

traits_l <- read_csv("2_data/2_clean/traits/traits_l.csv") %>%
  mutate(across(ID:group, as.factor))

global_traits <- read_csv("2_data/1_raw_data/global_traits/TTT_cleaned_dataset_v1.csv")

try_data <- rtry_import("2_data/1_raw/traits/try_data.txt") #%>% 
#  select(ObservationID, SpeciesName, TraitID, TraitName, #OrigValueStr) %>% 
#  filter(TraitID != 42) %>% 
#  na.omit() %>% 
#  group_by(ObservationID) %>% 
#  pivot_wider(names_from = TraitName, values_from = OrigValueStr)
```

```{r}
# community composition data (long)
community <- read_csv("2_data/2_clean/sf_community.csv") 
```

# Wrangling
```{r}
global_traits_w <- global_traits %>%
  select(2:4, SiteName, Trait, Value) %>% 
  pivot_wider(names_from = Trait, values_from = Value) %>% 
```



# taxonomic data
```{r}
classification <- read_delim("../../1_data/TRY_data/classification.csv", delim = "\t")
```


# exploration
```{r}
try_data_w <- try_data_w %>% 
  filter(height > 0)
```

```{r}
species_traits <- try_data_filtered %>% 
  group_by(SpeciesName) %>% 
  summarise(across(c(height, LDMC, SLA, N, d15N, C, d13C, CN_ratio), 
                   ~ mean(.x, na.rm = TRUE), 
                   .names = "{.col}")) %>% 
  column_to_rownames(var = "SpeciesName")
```

```{r}
try_data_w %>% 
  filter(N < 400) %>% 
  ggplot(aes(y = N)) + 
  geom_boxplot()

trait_data_pooled %>% 
  filter(species == "Empetrum nigrum") %>% 
  ggplot(aes(x = treatment, y = CN_ratio)) + 
  geom_boxplot()
```

