---
title: "multivariate_trait_stats"
author: "Liyenne"
date: "2025-05-23"
output: html_document
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = here::here("outputs")
    )
  })
cache: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup
```{r}
script_dir <- dirname(rstudioapi::getActiveDocumentContext()$path)
setwd(file.path(script_dir, "..", ".."))

# data handling
library(tidyverse)
library(broom)
library(purrr)

# analysis
library(vegan)
library(gllvm)
library(lme4)
library(pairwiseAdonis)

# diagnostics
library(fitdistrplus)
library(AICcmodavg)
library(DHARMa)

# visualization
library(ggplot2)
library(ggrepel)
library(ggordiplots)
library(ggvegan)

library(corrplot)
library(gclus)

conflicted::conflicts_prefer(dplyr::filter)
conflicted::conflicts_prefer(dplyr::select)
conflicted::conflicts_prefer(AICcmodavg::AICc)
```

# Data import
```{r data import}
# trait data
traits_no_chem <- read_csv("2_data/2_clean/traits/traits_no_chem_w.csv") %>% 
  mutate(across(1:10, as.factor))

traits <- read_csv("2_data/2_clean/traits/traits_w.csv") %>% 
  mutate(across(1:10, as.factor))

boot_traits <- read_csv("2_data/2_clean/traits/bootstrapped_traits_bmWeighted.csv") %>% 
  mutate(across(1:6, as.factor)) 
```

```{r}
# community composition data (long)
community <- read_csv("2_data/2_clean/sf_community.csv") %>% 
  mutate(across(1:10, as.factor))

# species list 
spec_list <- read_csv("2_data/1_raw/community/2025/sf_vp_species_list.csv") %>% 
  mutate(across(1:5, as.factor))
```

# PCA 
```{r}
traits %>% 
  na.omit() %>% 
  GGally::ggpairs(columns = c(11, 15:21), 
          mapping = aes(color = habitat))

ggsave("3_output/1_figures/traits/trait_plot_matrix.tif", height = 10, width = 10)
```

## species traits
```{r}
species_traits <- traits %>% 
  filter(complete.cases(.)) %>% 
  group_by(species) %>% 
  summarise(plant_height = mean(height), 
            LDMC = mean(LDMC), 
            SLA = mean(SLA), 
            N = mean(wN), 
            d15N = mean(d15N), 
            C = mean(wC), 
            d13C = mean(d13C), 
            CN_ratio = mean(CN_ratio)) %>% 
  column_to_rownames(var = "species")
```

```{r}
species_pca <- species_traits %>% 
  scale() %>% 
  rda()

summary(species_pca)

# extract PCA scores
species_scores <- scores(species_pca, display = "sites", choices = 1:2) %>% 
  as.data.frame() %>% 
  rownames_to_column("species") %>% 
  left_join(spec_list)

trait_scores <- scores(species_pca, display = "species", choices = 1:2) %>% 
  as.data.frame() %>% 
  rownames_to_column("trait")


```

```{r}
species_pca %>% 
  eigenvals() %>% 
  {. / sum(.)} %>% 
  mean(); summary(species_pca) # PC1, PC2 and PC3 are larger than the mean

eigenvals(species_pca); bstick(species_pca) # only PC1 significant according to broken stick values

scores(species_pca, display = "sites", choices = 1:8) %>% 
  cor() # no redundancy between PC1 and PC2
```

### ANOVA on PCA scores
```{r}

```


```{r}
trait_labs <- c("Plant~height", "LDMC", "SLA",  "'%'~N", "delta^15*N", "'%'~C", "delta^13*C", "C:N~ratio")
names(trait_labs) <- c("plant_height", "LDMC", "SLA",  "wN", "d15N", "wC", "d13C", "CN_ratio")

ggplot() +
  geom_hline(yintercept = 0, linetype = "dotted", alpha = 0.8) + 
  geom_vline(xintercept = 0, linetype = "dotted", alpha = 0.8) +
  geom_segment(data = trait_scores, aes(x = 0, y = 0, xend = 0.9 * PC1, yend = 0.9 * PC2), arrow = arrow(type = "closed", length = unit(0.1, "inches")), color = "gray") +
  geom_point(data = species_scores, aes(x = PC1, y = PC2, color = group), size = 3, alpha = 0.70) + # add the point markers
  geom_text_repel(data = species_scores, aes(x = PC1, y = PC2, label = species, color = group), size = 3.5,  alpha = 0.7) +  # add the species labels
  geom_label(data = trait_scores, aes(PC1, PC2, label = trait_labs), col = "navy", label.size = NA, fill = NA, parse = TRUE) +
  #geom_text(data = data_scores, aes(x = NMDS1, y = NMDS2, label = plot), vjust=0) +  # add the site labels
  #coord_equal() +
  theme_classic() +
  #guides(color = guide_legend(override.aes = list(shape = NA))) +
  theme(panel.border = element_rect(color = "black", fill = NA, size = 1), 
        strip.background = element_rect(color = "black", size = 1),
        legend.position = "bottom",
        legend.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm")) + 
  guides(color = guide_legend(override.aes = list(label = ""))) + 
  labs(x = "PC1 (41%)", y = "PC2 (20%)", color = "Functional group") 
  
ggsave("3_output/1_figures/traits/species_pca.tif", height = 6, width = 6)
```

## traits (with chem)
```{r}
traits_pca <- traits %>% 
  filter(complete.cases(.)) %>% 
  column_to_rownames(var = "ID") %>% 
  select(height, LDMC:CN_ratio) %>% 
  scale() %>% 
  rda()

summary(traits_pca)

site_scores <- as.data.frame(traits_pca$CA$u[, 1:2])
site_scores$ID <- as.factor(rownames(site_scores))
trait_scores <- as.data.frame(traits_pca$CA$v[, 1:2])
trait_scores$trait <- as.factor(rownames(trait_scores))


site_scores <- traits %>%
  select(ID:group) %>% 
  right_join(site_scores)

site_scores[, 11:12] <- site_scores[, 11:12] * 2.5
```

```{r}
trait_labs <- c("Plant~height", "LDMC", "SLA",  "'%'~N", "delta^15*N", "'%'~C", "delta^13*C", "C:N~ratio")
names(trait_labs) <- c("plant_height", "LDMC", "SLA",  "wN", "d15N", "wC", "d13C", "CN_ratio")

ggplot() +
  geom_hline(yintercept = 0, linetype = "dotted", alpha = 0.8) + 
  geom_vline(xintercept = 0, linetype = "dotted", alpha = 0.8) +
  geom_segment(data = trait_scores, aes(x = 0, y = 0, xend = 0.9 * PC1, yend = 0.9 * PC2), arrow = arrow(type = "closed", length = unit(0.1, "inches")), color = "gray") +
  geom_point(data = site_scores, aes(x = PC1, y = PC2, color = group), size = 3, stroke = 1, alpha = 0.70) + # add the point markers
  geom_label(data = trait_scores, aes(PC1, PC2, label = trait_labs), col = "navy", label.size = NA, fill = NA, parse = TRUE) +
  #geom_text(data = data_scores, aes(x = NMDS1, y = NMDS2, label = plot), vjust=0) +  # add the site labels
  #coord_equal() +
  theme_classic() +
  #guides(color = guide_legend(override.aes = list(shape = NA))) +
  theme(panel.border = element_rect(color = "black", fill = NA, size = 1), 
        strip.background = element_rect(color = "black", size = 1),
        legend.position = "bottom",
        legend.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm")) + 
  labs(x = "PC1 (42%)", y = "PC2 (17%)", color = "Functional group") 

ggsave("3_output/1_figures/traits/traits_pca.tif", height = 6, width = 6)
```

## traits (no chem)
```{r}
traits_no_chem_pca <- traits_no_chem %>% 
  filter(complete.cases(.)) %>% 
  column_to_rownames(var = "code") %>% 
  select(height, LDMC, SLA) %>% 
  scale() %>% 
  rda()

summary(traits_no_chem_pca)

site_scores <- as.data.frame(traits_no_chem_pca$CA$u[, 1:2])
site_scores$ID <- as.factor(rownames(site_scores))
trait_scores <- as.data.frame(traits_no_chem_pca$CA$v[, 1:2])
trait_scores$trait <- as.factor(rownames(trait_scores))

site_scores <- traits_no_chem %>%
  select(code:group) %>% 
  rename(ID = code) %>% 
  right_join(site_scores)

site_scores[, 11:12] <- site_scores[, 11:12] * 2.5
```

```{r}
ggplot() +
  geom_hline(yintercept = 0, linetype = "dotted", alpha = 0.8) + 
  geom_vline(xintercept = 0, linetype = "dotted", alpha = 0.8) +
  geom_segment(data = trait_scores, aes(x = 0, y = 0, xend = 0.9 * PC1, yend = 0.9 * PC2), arrow = arrow(type = "closed", length = unit(0.1, "inches")), color = "gray") +
  geom_point(data = site_scores, aes(x = PC1, y = PC2, color = habitat), size = 3, alpha = 0.70) + # add the point markers
  geom_label(data = trait_scores, aes(PC1, PC2, label = trait), col = "navy", label.size = NA, fill = NA) +
  #geom_text(data = data_scores, aes(x = NMDS1, y = NMDS2, label = plot), vjust=0) +  # add the site labels
  #coord_equal() +
  scale_colour_manual(values = c("#917D53", "#667E4E", "#A8AA97")) +
  scale_fill_manual(values = c("#917D53", "#667E4E", "#A8AA97")) +
  theme_classic() +
  theme_classic() +
  #guides(color = guide_legend(override.aes = list(shape = NA))) +
  theme(panel.border = element_rect(color = "black", fill = NA, size = 1), 
        strip.background = element_rect(color = "black", size = 1)) + 
  labs(x = "PC1 (49%)", y = "PC2 (15%)") 
```

## community traits
```{r}
plot_traits <- boot_traits_bm %>% 
  group_by(plot, trait) %>% 
  summarise(boot_mean = mean (mean)) %>% 
  pivot_wider(id_cols = plot, names_from = trait, values_from = boot_mean) %>% 
  column_to_rownames(var = "plot") %>% 
  select(-c(dweight, fweight, leafa)) 

plot_pca <- plot_traits %>% 
  scale() %>% 
  rda()

summary(plot_pca)
```

```{r}
# extract PCA scores
plot_scores <- scores(plot_pca, display = "sites", choices = 1:8) %>% 
  as.data.frame()

# extract and arrange meta data from boot_traits_bm
pca_meta_data <- boot_traits_bm %>% 
  select(plot, habitat, site, treatment) %>%  
  distinct() %>% 
  filter(plot %in% rownames(plot_traits)) %>% 
  arrange(match(plot, rownames(plot_traits))) %>%  
  column_to_rownames(var = "plot")

all(rownames(plot_scores) == rownames(pca_meta_data)) # PCA scores and meta data match!

# PERMANOVA on PCA scores [how many axes?]
x <- pca_meta_data %>% 
  filter(habitat == "ridge")
y <- plot_scores[rownames(x), ]
adonis2(y ~ treatment, data = x, 
        method = "euclidian", by = "terms")

pairAdonis_results <- map_dfr(unique(pca_meta_data$habitat), ~ {
  x <- pca_meta_data %>% 
    filter(habitat == .x)  # ← Use .x instead of hab
  y <- plot_scores[rownames(x), ]
  
  pairwise_result <- pairwise.adonis2(y ~ treatment, 
                                      method = "euclidian", 
                                      data = x)
  
  as.data.frame(pairwise_result) %>%
    mutate(habitat = .x,  # ← Use .x
           comparison = rownames(.))
}) %>%
  relocate(habitat, comparison)

write.csv(pairAdonis_results, "3_output/2_statistics/traits/pairwise_adonis_traits.csv", row.names = FALSE)
```

```{r}
plot_pca %>% 
  eigenvals() %>% 
  {. / sum(.)} %>% 
  mean(); summary(plot_pca) # PC1 and PC2 are larger than the mean

eigenvals(plot_pca); bstick(plot_pca) # only PC1 significant according to broken stick values

cor(plot_scores) # no redundancy between PC1 and PC2
```

### ANOVA on PCA scores
```{r}
site_scores <- scores(plot_pca, display = "sites", choices = 1:2) %>% 
  as.data.frame() %>% 
  rownames_to_column("plot")

trait_scores <- scores(plot_pca, display = "species", choices = 1:2) %>% 
  as.data.frame() %>% 
  rownames_to_column("trait") %>% 
  mutate(PC1 = PC1 * -1, 
         PC2 = PC2 * -1)

site_scores <- boot_traits_bm %>%
  select(plot:site) %>% 
  unique() %>% 
  right_join(site_scores) %>% 
  mutate(PC1 = PC1 * -1, 
         PC2 = PC2 * -1)
```
 
```{r}
# Modelling PCA scores
y <- site_scores %>% 
  filter(habitat == "heath")

dist <- fitdist(y$PC2, "norm")
plot(dist)

fit <- lm(PC1 ~ treatment, data = y); AICc(fit)

fit <- lm(PC2 ~ treatment, data = y); AICc(fit)

# fit <- site_scores %>% 
#   lmer(PC1 ~ treatment + (1 | site), data = .); AICc(fit)

# fit <- site_scores %>%
#   lmer(PC1 ~ habitat * treatment + (1 | site), data = .); AICc(fit)

summary(fit)
car::Anova(fit, type = "II") %>% 
  tidy()

emm <- emmeans(fit, ~ treatment | habitat)
pairs(emm, adjust = "tukey") %>%
  as.data.frame()

plot(emmeans(fit, ~ treatment | habitat))
```

```{r}
PC_anovas <- map_dfr(unique(site_scores$habitat), ~ {
  y <- site_scores %>%
    filter(habitat == .x)
  
  fit1 <- lm(PC1 ~ treatment, data = y); AICc(fit)
  model_output <-  car::Anova(fit1, type = "II") %>%
    tidy() %>% 
    mutate(PC = "PC1")
  
  fit2 <- lm(PC2 ~ treatment, data = y); AICc(fit)
  model_output <-  car::Anova(fit2, type = "II") %>%
    tidy() %>% 
    mutate(PC = "PC2") %>% 
    bind_rows(model_output, .)
  
  model_output %>% 
    mutate(habitat = .x) %>% 
    relocate(habitat, PC)
}); PC_anovas
```


```{r}
simulationOutput <- simulateResiduals(fittedModel = fit)
plot(simulationOutput)
testDispersion(simulationOutput); rm(simulationOutput)

x <- check_collinearity(fit)
plot(x); rm(x)
```


```{r}
trait_labs <- c("C:N~ratio", "delta^13*C", "delta^15*N", "Plant~height", "LDMC", "SLA", "'%'~C",  "'%'~N")
names(trait_labs) <- c("CN_ratio", "d13C", "d15N", "height", "LDMC", "SLA", "wC",  "wN")

ggplot() +
  geom_hline(yintercept = 0, linetype = "dotted", alpha = 0.8) + 
  geom_vline(xintercept = 0, linetype = "dotted", alpha = 0.8) +
  geom_segment(data = trait_scores, aes(x = 0, y = 0, xend = 0.9 * PC1, yend = 0.9 * PC2), arrow = arrow(type = "closed", length = unit(0.1, "inches")), color = "gray") +
  geom_point(data = site_scores, aes(x = PC1, y = PC2, color = habitat, shape = treatment), size = 3, stroke = 1, alpha = .7) + # add the point markers
  geom_label(data = trait_scores, aes(PC1, PC2, label = trait_labs), col = "navy", label.size = NA, fill = NA, parse = TRUE) +
  #geom_text(data = data_scores, aes(x = NMDS1, y = NMDS2, label = plot), vjust=0) +  # add the site labels
  #coord_equal() +
  scale_shape_manual(values = c(16, 8)) +
  scale_colour_manual(values = c("#917D53", "#667E4E", "#A8AA97")) +
  scale_fill_manual(values = c("#917D53", "#667E4E", "#A8AA97")) +
  theme_classic() +
  #guides(color = guide_legend(override.aes = list(shape = NA))) +
  theme(panel.border = element_rect(color = "black", fill = NA, size = 1), 
        strip.background = element_rect(color = "black", size = 1),
        legend.position = "bottom",
        legend.box = "vertical",     
        legend.box.just = "left", 
        legend.spacing.y = unit(0, "cm"), 
        legend.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm")) + 
  labs(x = "PC1 (75%)", y = "PC2 (14%)") 

ggsave("3_output/1_figures/traits/plot_pca.tif", height = 6, width = 6)
```

# RDA
```{r}

```


# Change vs PCA
```{r}
# calculate biomass differences (sf-ctl) per species per site
biomass_diff <- community %>% 
  mutate(site = str_sub(plot, 1, 2)) %>% 
  #pivot_wider(names_from = treatment, values_from = biomass) %>% 
  #group_by(habitat, site, spec, group) %>% 
  #summarise(biomass_diff = sum(snowfence - control, na.rm = TRUE)) %>% 
  left_join(species_scores)
```

```{r}
biomass_diff %>% 
  filter(part == "leaf") %>% 
  ggplot(aes(x = PC1, y = hits, color = treatment)) +
  geom_point()
```

